<?php
/**
 * The template for displaying the footer on the site.
 * It does not use tailwind, it's SCSS file can be found at ./assets/src/sass/components/footer.scss.
 * The "Footer Columns" generated by PHP can be configured in functions.php.
 *
 * Contains the footer of the site as well as WP's required code and the closing body and HTML tags.
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package WordPress
 * @subpackage Status_Glo
 * @since 1.0.0
 */
?>

<!--Start Footer-->
<footer class="footer">
    <div class="footer-left">

        <!--Company Logo-->
        <img src="https://statusglo.com/wp-content/uploads/2021/09/Icon-White-Small.png" alt = "Company Logo">
        <div class="left-inner">
            <!--Company Info-->
            <h3>Status Glo</h3>
            <p class="phone-number">523 Cupola Way </p>
            <p class="phone-number">Knoxville TN 37918</p>
            <p class="phone-number"><a href="tel:8652473804">865-247-3804</a></p>
            <p class="phone-number">Open Monday - Friday, 9AM to 5PM</p>
            <p class="phone-number">booking@statusglo.com</p>

            <p class="phone-number"></p>
        </div>
    </div>

    <div class="footer-right">
        <div class="right-inner">
            <!--Wordpress Generated Link Lists-->
            <?php wp_nav_menu( array( 'theme_location' => 'footer-column-1' ) ); ?>
            <?php wp_nav_menu( array( 'theme_location' => 'footer-column-2' ) ); ?>
        </div>

    </div>
    <div class="footer-bottom">
        <div class="bot-inner">

            <!--Copyright Info-->
            <p class = "text-lg">Bonded, Licensed and Insured</p>
            <p>© <?php echo date("Y"); ?> Status Glo</p>

            <!--Socials, icons from: https://fontawesome.com/ -->
            <div class="footer-icons">
            <a href="https://www.facebook.com/gotostatusglo"><i class="fa fa-facebook"></i></a>
            <a href="https://www.instagram.com/gotostatusglo/"><i class="fa fa-instagram"></i></a>
        </div>
    </div>
</footer>
<!--End Footer-->


<!--Wordpress Requires This-->
<?php wp_footer(); ?>

</body>
</html>

